# Generated by Django 3.1.1 on 2020-09-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='public',
            new_name='visible',
        ),
    ]
